# Site
name: "Jungeun's tech bolg"
title: "Jungeun"
description: "간단한 기술 정리하는 블로그"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "/"
url: "https://jungeunkwon.github.io/"
disqus: "JungeunKwon"
include: ["_pages"]
permalink: /:title/
cover: "assets/images/cover.png"

# Authors
authors:
  Jungeun:
    name: Jungeun Kwon
    display_name: 쩡으니
    email: wjdwjd95@gmail.com
    web: https://github.com/JungeunKwon
    avatar: https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-19/s150x150/36976677_197009920980525_9040153933212811264_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_ohc=0_vJyY-tRXQAX_OQEx5&oh=49f961fbec8593ff5646a79ec74d28bd&oe=5F3124F4
    instagram: https://instagram.com/jjeun_2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
