# Site
name: "Jungeun's tech bolg"
title: "Jungeun"
description: "간단한 기술 정리하는 블로그"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "https://jungeunkwon.github.io"
url: "https://jungeunkwon.github.io/"
disqus: "JungeunKwon"
include: ["_pages"]
permalink: /:title/
cover: "assets/images/cover.png"
google_analytics: "UA-175344734-1"

# Authors
authors:
  Jungeun:
    name: Jungeun Kwon
    display_name: 쩡으니
    email: wjdwjd95@gmail.com
    web: https://github.com/JungeunKwon
    avatar: "/assets/images/avatar.png"
    instagram: https://instagram.com/jjeun_2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
#markdown: kramdown
highlighter: rouge

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
